name: Format

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
      - "**.md"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "25"

      - run: npm install -g prettier@3.6.2
      - run: prettier --check "**/*.{yml,yaml}"
      - run: prettier --check --prose-wrap always "**/*.md"
