name: Build Python Wheels

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.platform.name }} (Py ${{ matrix.python }})
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ["3.12", "3.13", "3.14"]
        platform:
          - name: linux-x86_64
            os: ubuntu-latest
            args: --release -F python --out dist --compatibility manylinux_2_34
          - name: windows-x86_64
            os: windows-latest
            args: --release -F python --out dist
          - name: macos-x86_64
            os: macos-13
            args: --release -F python --out dist
          - name: macos-aarch64
            os: macos-14
            args: --release -F python --out dist
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: dtolnay/rust-toolchain@61a77d273cb53ffc500b8bf0daf1523ccdbf1529 # stable
        with:
          toolchain: stable
      - uses: astral-sh/setup-uv@26d44e6b3946bf660157bf0ef793edeefc7cc45e # v3.1.1
      - name: Install Python ${{ matrix.python }}
        run: uv python install ${{ matrix.python }}
      - name: Build wheel (${{ matrix.platform.name }}, Py ${{ matrix.python }})
        run: uv run --python ${{ matrix.python }} maturin build ${{ matrix.platform.args }}
      - name: Upload wheels
        uses: actions/upload-artifact@0b255cbe3472e179850acb9b47dbefbae528837d # v4.3.4
        with:
          name: ${{ matrix.platform.name }}-py${{ matrix.python }}-wheels
          path: dist/*.whl
          if-no-files-found: error

  release:
    name: Attach wheels to release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - uses: actions/download-artifact@973fd186ad5f56c6ef5690da87c4ff4c8e7cdafc # v4.1.0
        with:
          path: wheelhouse
      - name: Publish release assets
        uses: softprops/action-gh-release@69320dbe8719d79f926ba70b1f5a6dbef04510b4 # v2.0.4
        with:
          files: wheelhouse/**/*.whl
